-------------------------------------------------------------------------------
Test set: integration.datalayer.customer.CreateCustomerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.117 s <<< FAILURE! - in integration.datalayer.customer.CreateCustomerTest
integration.datalayer.customer.CreateCustomerTest  Time elapsed: 2.117 s  <<< ERROR!
java.lang.ExceptionInInitializerError
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mysql, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}


